project:
  type: website
  output-dir: docs

website:
  title: "Louie Neri"
  navbar: false
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

