project:
  type: website
  output-dir: docs

website:
  title: "Louie Neri"
  navbar:
    left:
      - href: index.qmd
        text: "About me"
      - href: https://louieneri.github.io/nursingthenumbers/
        text: "Nursing the numbers blog"
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

