project:
  type: website
  output-dir: docs

website:
  favicon: headshot.jpg
  title: "Louie Neri"
  navbar: false
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    mainfont: "Times New Roman"
    
editor: visual

